"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
PACKAGES = ['backend']
DATA_FILES = [
    ("js", ["frontend/dist/js/bundle.js"]),
    ("html", ["frontend/dist/html/index.html"]),
    ("css", ["frontend/dist/css/bundle.css"]),
]
OPTIONS = {
    'argv_emulation': True,
    'iconfile': './assets/AppIcon.icns',
    'plist': {
        'CFBundleIdentifier': 'se.ojoj.messagearchive',
        'CFBundleName': 'MessageArchive',
        'CFBundleVersion': '0.0.1',
        'CFBundleShortVersionString': '0.0.1',
        'NSHumanReadableCopyright': 'Copyright?',
    },
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
